<?php
/**
 * @file
 * glacier_content_blocks.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function glacier_content_blocks_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Container narrow (limited width)',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'rh_action' => NULL,
    'rh_redirect' => NULL,
    'rh_redirect_response' => NULL,
    'uuid' => '2d92b5ee-f407-4012-b310-644cc3d267aa',
    'vocabulary_machine_name' => 'content_block_styles',
    'name_field' => array(
      'de' => array(
        0 => array(
          'value' => 'Container schmal (begrenzte Breite)',
          'format' => NULL,
          'safe_value' => 'Container schmal (begrenzte Breite)',
        ),
      ),
      'en' => array(
        0 => array(
          'value' => 'Container narrow (limited width)',
          'format' => NULL,
          'safe_value' => 'Container narrow (limited width)',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Container narrow (limited width)',
          'format' => NULL,
          'safe_value' => 'Container narrow (limited width)',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_content_block_classes' => array(
      'und' => array(
        0 => array(
          'value' => 'u-container-narrow',
          'format' => NULL,
          'safe_value' => 'u-container-narrow',
        ),
      ),
    ),
    'name_original' => 'Container narrow (limited width)',
    'entity_translation_handler_id' => 'taxonomy_term-eid-2-0',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2,
          'revision_id' => 2,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1440757933,
          'changed' => 1442061372,
        ),
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2,
          'revision_id' => 2,
          'language' => 'de',
          'source' => 'en',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1440757947,
          'changed' => 1442061380,
        ),
      ),
    ),
    'description_original' => '',
  );
  $terms[] = array(
    'name' => 'Highlighted grey (grey background)',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'rh_action' => NULL,
    'rh_redirect' => NULL,
    'rh_redirect_response' => NULL,
    'uuid' => '393b4e63-e83b-4c7d-9fcf-e9539e0c8913',
    'vocabulary_machine_name' => 'content_block_styles',
    'name_field' => array(
      'de' => array(
        0 => array(
          'value' => 'Hervorgehoben grau (grauer Hintergrund)',
          'format' => NULL,
          'safe_value' => 'Hervorgehoben grau (grauer Hintergrund)',
        ),
      ),
      'en' => array(
        0 => array(
          'value' => 'Highlighted grey (grey background)',
          'format' => NULL,
          'safe_value' => 'Highlighted grey (grey background)',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Highlighted grey (grey background)',
          'format' => NULL,
          'safe_value' => 'Highlighted grey (grey background)',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_content_block_classes' => array(
      'und' => array(
        0 => array(
          'value' => 'o-island',
          'format' => NULL,
          'safe_value' => 'o-island',
        ),
      ),
    ),
    'name_original' => 'Highlighted grey (grey background)',
    'entity_translation_handler_id' => 'taxonomy_term-eid-3-0',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3,
          'revision_id' => 3,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1440757970,
          'changed' => 1442061384,
        ),
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3,
          'revision_id' => 3,
          'language' => 'de',
          'source' => 'en',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1440758011,
          'changed' => 1442061391,
        ),
      ),
    ),
    'description_original' => '',
  );
  $terms[] = array(
    'name' => 'Container (limited width)',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'rh_action' => NULL,
    'rh_redirect' => NULL,
    'rh_redirect_response' => NULL,
    'uuid' => '7f4c9199-3414-45a9-b6c1-4a0a29f6c070',
    'vocabulary_machine_name' => 'content_block_styles',
    'name_field' => array(
      'de' => array(
        0 => array(
          'value' => 'Container (begrenzte Breite)',
          'format' => NULL,
          'safe_value' => 'Container (begrenzte Breite)',
        ),
      ),
      'en' => array(
        0 => array(
          'value' => 'Container (limited width)',
          'format' => NULL,
          'safe_value' => 'Container (limited width)',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Container (limited width)',
          'format' => NULL,
          'safe_value' => 'Container (limited width)',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_content_block_classes' => array(
      'und' => array(
        0 => array(
          'value' => 'u-container',
          'format' => NULL,
          'safe_value' => 'u-container',
        ),
      ),
    ),
    'name_original' => 'Container (limited width)',
    'entity_translation_handler_id' => 'taxonomy_term-eid-4-0',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 4,
          'revision_id' => 4,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1440757695,
          'changed' => 1442061353,
        ),
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 4,
          'revision_id' => 4,
          'language' => 'de',
          'source' => 'en',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1440757720,
          'changed' => 1442061362,
        ),
      ),
    ),
    'description_original' => '',
  );
  $terms[] = array(
    'name' => 'Text center',
    'description' => NULL,
    'format' => 'filtered_html',
    'weight' => 0,
    'rh_action' => NULL,
    'rh_redirect' => NULL,
    'rh_redirect_response' => NULL,
    'uuid' => '8f78ff14-e0be-4b0c-8120-4b9f6ef8522f',
    'vocabulary_machine_name' => 'content_block_styles',
    'name_field' => array(
      'de' => array(
        0 => array(
          'value' => 'Text zentriert',
          'format' => NULL,
          'safe_value' => 'Text zentriert',
        ),
      ),
      'en' => array(
        0 => array(
          'value' => 'Text center',
          'format' => NULL,
          'safe_value' => 'Text center',
        ),
      ),
      'und' => array(
        0 => array(
          'value' => 'Text center',
          'format' => NULL,
          'safe_value' => 'Text center',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_content_block_classes' => array(
      'und' => array(
        0 => array(
          'value' => 'u-text-align-center',
          'format' => NULL,
          'safe_value' => 'u-text-align-center',
        ),
      ),
    ),
    'name_original' => 'Text center',
    'entity_translation_handler_id' => 'taxonomy_term-eid-5-0',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 5,
          'revision_id' => 5,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1440757903,
          'changed' => 1442061335,
        ),
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 5,
          'revision_id' => 5,
          'language' => 'de',
          'source' => 'en',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1440757912,
          'changed' => 1442061347,
        ),
      ),
    ),
    'description_original' => '',
  );
  return $terms;
}
